extract = 'total_dyn_stack_spills: (\d+)'
benchmarks = '../benchmarks/core/*.bril'


[runs.total_dyn_stack_spills]
pipeline = [
    "bril2json",
    "python personal_ssa.py",
    "python new_loop_normalization.py",
    "python register_allocation.py 5",
    "brili -p {args}",
]
